version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=database-1.c1kexfmljm5a.us-east-1.rds.amazonaws.com
      - DB_USER=dev_cris
      - DB_PASSWORD=cristo1989
      - DB_NAME=soft_seguros_db
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=cristo1989
      - MYSQL_USER=dev_cris
      - MYSQL_PASSWORD=cristo1989
      - MYSQL_DATABASE=soft_seguros_db
      - MYSQL_HOST=database-1.c1kexfmljm5a.us-east-1.rds.amazonaws.com
